apiVersion: v1
kind: Service
metadata:
  name: k8s-labs-nginx-service
  labels:
    app: k8s-labs-nginx
    environment: development
    company: kubernetes-laboratories
spec:
  selector:
    app: k8s-labs-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
